### ISSUE TITLE
How Change Default Icon

### ISSUE THREAD

**Issue by ma9091** [ElectronNET/Electron.NET#124]

**Comment by kwakuduahc1** [comment]
You may have to fork your own and then change the icons.

**Comment by R00iBaard** [comment]
I find this crazy you need to fork to be able to do this???

dotnet electronize build /target win /electron-params "--icon="assets/app-icon/win/lci.ico""
I tried this, produces the following which looks right -

electron-packager . --platform=win32 --arch=x64 --icon=assets/app-icon/win/lci.ico --out="C:\Users\davidroux\Halo Software\Halo\DeviceManagement\bin\desktop" --overwrite

However get the following error 

Packaging app for platform win32 x64 using electron v1.7.11
WARNING: Found 'electron' but not as a devDependency, pruning anyway
rcedit.exe failed with exit code 1. Cannot open icon file 'a'
Fatal error: Unable to set icon

Also attempted inside startup.cs but not winning there :

`            var browserWindow = await Electron.WindowManager.CreateWindowAsync(new BrowserWindowOptions
            {
                Center = true,
                Width = 1152,
                Height = 864,
                Show = true
                Icon = @"~/assets/app-icon/win/lci.ico"
            });`

**Comment by robertmuehsig** [comment]
Hi - this is indeed quite stupid to fork the whole project. AFAIK icons are stupid to setup (at least the macOS icons are created in a different way) but I might be wrong here. Could you tell me how the electron-packager needs to be invoked to insert the correct icons?

**Comment by R00iBaard** [comment]
Hey @robertmuehsig, thanks for the fast reply! I was using this link to figure out what I provided above : https://www.christianengvall.se/electron-packager-tutorial/#windows

**Comment by arjo1203** [comment]
Hey @ma9091 it looks like there are two issues with the way you are passing the path of the icon to the electron-packager via the ElectronNet command:
1. The icon path must be an absolute path, just like the --out option
 ` --out="C:\Users\davidroux\Halo Software\Halo\DeviceManagement\bin\desktop"`
2. You're missing the quotation marks, which is why the system is trying to open 'a' icon file

**NOTE** how the out path had quotation marks around it

Your example should be modified like so,
    `--icon=assets/app-icon/win/lci.ico`          ====>   `--icon="C:\absolute\path\to\icon.ico"`

In order to produce this with ElectronNet, you must format the icon path like so,
`"--icon="assets/app-icon/win/lci.ico""` ==> `"--icon=\"assets/app-icon/win/lci.ico\""`

Doing this, includes the quotation marks and will resolve your issue.

**Comment by GregorBiswanger** [comment]
Available with the next Electron.NET update.
