### ISSUE TITLE
Unable to build (The given key was not present in the dictionary.)

### ISSUE THREAD

**Issue by Khaoz-Topsy** [ElectronNET/Electron.NET#176]
Hi,

I am struggling to get Electron.Net to build my project, I can use ```dotnet electronize start``` and that works properly but I cannot seem to get it to build. My project is dotnet core MVC
![image](https://user-images.githubusercontent.com/15005470/47358158-3f165980-d6c9-11e8-93e7-21bc19d2fd2e.png)

ElectronNET.CLI Version: 0.0.9.0
Microsoft.AspNetCore 2.1.1

**Comment by robertmuehsig** [comment]
Can you share the your sample application?

**Comment by Khaoz-Topsy** [comment]
Thanks for the super fast reply 😀
Here is most of the application 
https://github.com/Khaoz-Topsy/electron.NetTimesheetsApp

**Comment by Khaoz-Topsy** [comment]
In pushing the code to that github repo, I used hyper instead of bash, and then it built. So it seems that I am only unable to use ```dotnet electonize build /target win``` in bash

**Comment by kwakuduahc1** [comment]
The problem is your .csproj. I ran into the same issue today. I had inadvertently modified a part of my csproj i couldn't remember.

Try copying and pasting a working csproj of a different project that works. If the need be, reinstall all nuget packages that will be missing.

Then lastly, avoid updating the netcore packages, e.g. entityframework etc. This project only works with netcore 2 and updating any dependency to a different version can be fatal

**Comment by Khaoz-Topsy** [comment]
Well without changing the files, I can run `dotnet electonize build /target win` from hyper or the cmd, but not from bash

**Comment by robertmuehsig** [comment]
We updated our nuget packages: Maybe this will help (and make sure to read the readme, because the ElectronNET CLI is now a global dotnet tool.

**Comment by robertmuehsig** [comment]
If the issue is still not solved just let me know.

**Comment by pedromrpinto** [comment]
I had the same issue with version 0.0.11.0

I was using the following comand in git bash:
      `electronize build /target win`
using windows cmd solved the issue
