### ISSUE TITLE
Unexpected firewall warnings

### ISSUE THREAD

**Issue by torman119** [ElectronNET/Electron.NET#181]
When we start the final electron app we get 2 firewall warnings popping up (running on windows 10). 
For instance when building and running the Electron.Net sample music player, we get a firewall warning for "ElectronNET.Host" and one for "myelectronmusicplayer.exe". 
Does anybody know why we get these warnings? Why do we get 2 of them? How can we avoid them for our users?

**Comment by ctrl-d** [comment]
Had same issue & stopped looking into it becouse of that

**Comment by RogerDodger123** [comment]
I have solved the firewall prompt when it comes to the api. This was done by just resetting the bind:
```
WebHost.CreateDefaultBuilder(args)
                .UseElectron(args)
                .UseUrls($"http://localhost:{BridgeSettings.WebPort}")
                .UseStartup<Startup>();
```

but the issue lies here:
https://github.com/ElectronNET/Electron.NET/blob/5a676cb76aee7069cfe15fd09aca2c52e5498447/ElectronNET.API/WebHostBuilderExtensions.cs#L34

The api is being bound to `0.0.0.0`

**Comment by robertmuehsig** [comment]
Mh - would " .UseUrls("http://localhost:" + BridgeSettings.WebPort);" trigger the same Firewall Warning? @RogerDodger123 ?

**Comment by robertmuehsig** [comment]
This should be fixed in the next update.
