### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by wendellm** [ElectronNET/Electron.NET#24]
I cloned this repo and used the build.cmd but I get the following error

```
dotnet restore
  Restore completed in 27,98 ms for D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
  Restoring packages for D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj...
D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102: Unable to find package ElectronNET.API with version (>= 1.0.0)\r
D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102:   - Found 5 version(s) in nuget.org [ Nearest version: 0.0.5 ]\r
D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj : error NU1102:   - Found 0 version(s) in LocalDev
  Restore failed in 915,28 ms for D:\repositories\Electron.NET\ElectronNET.WebApp\ElectronNET.WebApp.csproj.
```

Am I missing something?

**Comment by robertmuehsig** [comment]
Hi
The build.cmd might be missleading. Currently it only builds the WebApp project, which requires that the API / CLI projects have been build. 

Try "buildAll.cmd" - this might take a while, because it builds the API and CLI. After that the real WebApp will be published for Win/Linux with the electron stuff. 

After a successful run of buildAll.cmd you should be able to use build.cmd/start.cmd.

I guess we need to a) rename those files or b) remove the build.cmd/start.cmd files, because AFAIK they might be not needed anymore. @GregorBiswanger

**Comment by robertmuehsig** [comment]
The build.cmd is now gone, please use buildAll.cmd. 

I'll close this and add some notes to the ReadMe.md. Hope this is OK.
