### ISSUE TITLE
In Development or Abandoned?

### ISSUE THREAD

**Issue by saad749** [ElectronNET/Electron.NET#242]
Is this project is still in development or abandoned?

**Comment by LeatonChuter** [comment]
I'd like to know as well, I have a new project coming up that this would be perfect for but I'm running into issues quickly enough that community and developer participation will make or break whether I can consider this stable enough to work with.

**Comment by GregorBiswanger** [comment]
Hi Community,
no, Electron.NET is not death :)
We have only a time problem. I´m daddy since 1,5 year and freelancer as trainer and consultant.
But the good news is, I have the complete next week time for working again on the next Version from Electon.NET.

BUT we need your help.. please feel free and push your "Pull requests" :)

Cheers,
Gregor

**Comment by GregorBiswanger** [comment]
by the way... we also gladly accept financial donations ... that would greatly increase the priority of further development :)

**Comment by meteorsnows** [comment]
Thanks. .NET 5 is coming and unified. Maybe updated together.

**Comment by grbd** [comment]
Just to mention I'm in the middle of doing a re-write / tidy up of the way the configuration is loaded for the ElectronNet.CLI to use Microsoft.Extensions.Configuration
so that it can optionally load a json file and has lots of options for different commands (like being able to pick pnpm or yarn instead of npm)

I'm not sure if it'll get accepted as it's quite a big change but once I'm finished with it I'll be interested on getting some feedback after I post a pull request

I've also got some other ideas such as setting up some documentation via Mkdocs which is a python based static site generator that reads in markdown files.
Another one would be placing the host files in a directory where the user could edit them prior to the build (so they could manually pick a newer version of electron)

**Comment by GregorBiswanger** [comment]
Hey Community, we do this open source work in our free time. If you'd like us to invest more time on it, please donate. Donation can be used to increase some issue priority. Thank you. https://donorbox.org/electron-net
