### ISSUE TITLE
Add electron.net template for vue.js and angular

### ISSUE THREAD

**Issue by miladbonakdar** [ElectronNET/Electron.NET#265]
I saw on your documents that you shared a template for React as a UI framework. 
Can you add a simple template for getting started with Vue js or Angular? 
I think it would be a good idea to add those two.
I am trying to use vue.js pure javascript for my app but I cannot use Vue templates because all of them using Vue cli to run.
I will appreciate if you at least give me a hint on how to do that.

**Comment by netpoetica** [comment]
Can you describe the problem in a bit more detail? What is your level of expertise in Vue and Angular? Because I think I could probably help you get started, but most likely, project templates for Vue and Angular would best be left in userland with Vue/Angular experts - maybe we could help you get the Electron.NET ecosystem synchronized with your Vue/Angular app and you could be the template creator :)

I am not very familiar with Vue CLI at all (seems crazy to me that a CLI tool would be used for a front-end app framework? Except for maybe the build process). If you can put together a sample repo and some step by step of what commands you are running, maybe we could see the disconnect and get it sorted

**Comment by johndab** [comment]
I've just created a template with Electron.NET and Vue by using [.NET Core VueCliMiddleware](https://github.com/EEParker/aspnetcore-vueclimiddleware)
Here: https://github.com/johndab/electron.net-vue

You can have standalone Vue project running independently and just proxy requests from .net to vue in development.
For production it just generates html and js static files.

The only issues I have is that `env.IsDevelopment()` doesn't work in `Startup.cs` with Electron.NET because the project is being published by the Electron.CLI.
And `AfterTargets="ComputeFilesToPublish"` in `.csproj` is executed every time I start the development - it should only run with `electronize build `

For now you need to modify it manually before building for production ( described [here](https://github.com/johndab/electron.net-vue#production) )
