### ISSUE TITLE
Does this support windows XP

### ISSUE THREAD

**Issue by pabeda-bt** [ElectronNET/Electron.NET#27]
Hello,
Does Electron.NET support windows xp? I can't find  what are the requirments.

Thanks.

**Comment by robertmuehsig** [comment]
Windows XP is not supported, because we use .NET Core 2 for our API, which only is supported in Windows 7 SP1 and above, see [.NET Core Requirements](https://github.com/dotnet/core/blob/master/release-notes/2.0/2.0-supported-os.md)

But even Windows 7 SP1 is currently not possible, because we just build for Windows 10 - this is tracked in this issue: https://github.com/ElectronNET/Electron.NET/issues/6

Sorry - the lowest Win OS level would be 7 SP1. 

We should add a requirement section in our readme.

**Comment by pabeda-bt** [comment]
Thank you Robert.
