### ISSUE TITLE
Unable to resotre DotNetCLI Reference

### ISSUE THREAD

**Issue by newblord** [ElectronNET/Electron.NET#28]
I grabbed a copy of the Music Player application written by you. 

when i run the command dotnet electronize init i get an error.

![image](https://user-images.githubusercontent.com/5922965/32382920-8e9cd31e-c084-11e7-9155-cb48706ec6ed.png)

I have tried running dotnet restore prior to this.  I have .Net Core 2.0 SDK installed and am using Visual Studio 2017.

**Comment by robertmuehsig** [comment]
Could you a "dotnet restore"?

**Comment by newblord** [comment]
Ive tried that but that doesnt seem to add the CLI reference.

**Comment by robertmuehsig** [comment]
This is (sadly) by design. CLI extensions can only be added through the .csproj.

I just cloned the project and it should look like something like this:

PS D:\Code\GitHub\electron.net-musicplayer-sample> dotnet restore
  Restoring packages for D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj...
  Restoring packages for D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj...
  Installing ElectronNET.CLI 0.0.5.
  Restore completed in 1.53 sec for D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj.
  Installing ElectronNET.API 0.0.5.
  Generating MSBuild file D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\obj\MyElectronMusicPlayer.csproj.nuget.g.props.
  Generating MSBuild file D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\obj\MyElectronMusicPlayer.csproj.nuget.g.targets.
  Restore completed in 6.43 sec for D:\Code\GitHub\electron.net-musicplayer-sample\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj.
PS D:\Code\GitHub\electron.net-musicplayer-sample>

**Comment by newblord** [comment]
This is what my command outputs:

![image](https://user-images.githubusercontent.com/5922965/32395971-5ce41b52-c0b1-11e7-9980-4a45860d2525.png)

I do have the dotnetclireference in the .csproj.  I assumed it would show up in that list if it actually got installed correctly.  For me it is not even installing hte CLI reference.

Do i need to have anything else installed besides .NET Core 2.0 SDK?

**Comment by robertmuehsig** [comment]
And dotnet electronize version doen't work? Maybe the Electron.NET CLI is already installed - it's hard to see from VS if it is there or not.

**Comment by newblord** [comment]
i cant use any of the dotnet electronize commands

**Comment by robertmuehsig** [comment]
Could you check if you have a electronnet.cli folder in the NuGet Cache?
Location: %userprofile%/.nuget/packages
And here: %userprofile%/.nuget/packages/.tools

If yes: Try to remove the electronnet.cli package there and do a new dotnet restore.

**Comment by newblord** [comment]
I just removed it and i got this:

PS C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master> dotnet restore --force
  Restoring packages for C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj...
  Restoring packages for C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj...
  Restore completed in 991.71 ms for C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj.
  Installing ElectronNET.CLI 0.0.5.
  Restore completed in 1.63 sec for C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master\MyElectronMusicPlayer\MyElectronMusicPlayer.csproj.
PS C:\Users\hiteshkpatel\Desktop\electron.net-musicplayer-sample-master> dotnet electronize init
No executable found matching command "dotnet-electronize"

**Comment by GregorBiswanger** [comment]
Try the default CMD.exe (Command Shell) - I got the same mysterious effects with PowerShell..

**Comment by newblord** [comment]
oh man that worked.  That is so weird that it would not work from Powershell or Nuget Package Manager.

Thanks for the help guys.

**Comment by GregorBiswanger** [comment]
You are welcome ;) 

normal I like PowerShell but the VS integration is terrible...

**Comment by R00iBaard** [comment]
Hey, looks like im getting this error as well via Visual Studio Professional 2017. Some details :
.NET Core 2.1.104
Electron.NET.API 0.0.9
Microsoft.AspNetCore.Mvc 2.0.3

Csproj :
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ElectronNET.API" Version="0.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.6" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.3" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="2.0.3" />
  </ItemGroup>
  <ItemGroup>
    <DotNetCliToolReference Include="ElectronNET.CLI" Version="0.0.9" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="electron.manifest.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>

Tried running dotnet electronize init from package manager as well as CMD. Cleared nuget cache often as well. Any ideas?

**Comment by fiodarsazanavets** [comment]
I see that this issue is closed, but I had the same problem under different circumstances. I've managed to resolve it, so I am posting this comment in case someone else encounters the same problem.

In my case, I was using CMD.exe from the start and getting the same error message. Initially, I was running the "dotnet electronize start" command from the root of the solution folder. However, when I moved into the folder that contained the .csproj file that contained "<DotNetCliToolReference Include="ElectronNET.CLI" Version="*" />" and ran the command again, it worked.
