### ISSUE TITLE
When running electronize init it deletes installed dependencies 

### ISSUE THREAD

**Issue by MordechaiHadad** [ElectronNET/Electron.NET#349]
**Description**: When I use electronize init it deletes all of my installed dependencies Including the Electron.NET API.

* **API-Version**: Latest
* **.NET Core Version**: Latest
* **Node.js Version**: Latest
* **Visual Studio Version**: 2019 Latest

Steps to Reproduce:

1. Install dependencies.
2. Use ``electronize init`` in CLI

**Comment by GregorBiswanger** [comment]
I tried to reproduce the problem. The first time I actually deleted nuget packages from the solution file. When I repeated it, there were no problems.

I think it is due to the following problem: If the project was created with the dotnet cli and then packages are installed in Visual Studio Nuget without first saving the VS Solution file.

I cannot fix this problem in the code. It is best to save everything in Visual Studio before you use the electronize init command. Then there should be no more problems.
