### ISSUE TITLE
IpcMain.RemoveAllListeners(string) is not removing the listeners

### ISSUE THREAD

**Issue by LandinMartensIQ** [ElectronNET/Electron.NET#365]
* **Version**: 7.30.2
* **Target**: .Net Core 3.1

In the C# lib, `IpcMain.RemoveAllListeners(string)` is not removing the listeners. After executing this function, my event listeners are still firing. 

Steps to Reproduce:

1. Register a listener using `IpcMain.On(channel_name)`
2. Wait for the event to be fired at least once from javascript
3. Now in C# after the event, call `IpcMain.RemoveAllListeners(channel_name)
4. Fire the event again within javascript
5. The listener registered at step 1 still fires

**Comment by GregorBiswanger** [comment]
I tested it with the current version and there were no problems. Possibly. your code will not be executed with RemoveAllListeners or it is due to the new Electron 8 version. Our latest update in version 8.31.1 will be released in the next few days.

![ElectronRemoveAllListeners](https://user-images.githubusercontent.com/7336300/79753317-02570d00-8316-11ea-88d2-e48635a42d88.gif)

**Comment by dlamon1** [comment]
Did you find a solution to your problem? I am having the same issue.

**Comment by EdmarPereira** [comment]
I have the same problem, I have electron and React and when you are using the app for a log time it becomes slow because the number of imports using ipc renderer. I tried to remove al listeners but it continues sending requests.
