### ISSUE TITLE
Upgrade to NET 5

### ISSUE THREAD

**Issue by realLiangshiwei** [ElectronNET/Electron.NET#491]
Hi team.
Are there any plans to upgrade to NET 5?

**Comment by GregorBiswanger** [comment]
Hi @realLiangshiwei, definitely!

**Comment by realLiangshiwei** [comment]
https://devblogs.microsoft.com/dotnet/announcing-net-5-0-rc-2/
RC2 is a “go live” release; we are supported using it in production. We can upgrade now.

**Comment by techmind-git** [comment]
I was wondering if we can use it with .net 5 with the current latest version since it was presented like that here: https://www.youtube.com/watch?v=KHSJQ0nELlY. Are there things that might not work since you've got this issue open and marked for a future milestone? I was a bit confused so maybe you can share some more on this. Thank you.

**Comment by aschaefer94** [comment]
Any ETA on this feature? We're wanting to update to 5.0 but can't until we can build our electron package.

**Comment by scottkuhl** [comment]
I've submitted a PR to address the upgrade to .NET and also upgraded TypeScript and all NuGet packages to the latest version.

**Comment by aschaefer94** [comment]
Just for everyone to know - I found that if you are updating your .NET project to .NET 5, as long as you have dotnet 3.1 on your machine (or your build server or whatever you're using) you can still run your project in the current version of Electron.NET.
