### ISSUE TITLE
Must electron packer be globally installed?

### ISSUE THREAD

**Issue by robertmuehsig** [ElectronNET/Electron.NET#50]
From this [comment](https://github.com/ElectronNET/Electron.NET/issues/36#issuecomment-343642402)

> You say

> "Be aweare that dotnet electonize build require that the electron packer is installed globally via npm."
> Using of global node modules is not very good idea. User should not be able to run commands as root.
> For what purpose u use global node modules? Just because u can do it?
> Can u just use node_modules folder from project?

Currently we assume that electron packer is installed globally and under Windows we even just install it globally. 

From the electron packer [page](https://github.com/electron-userland/electron-packager): 

> This module requires Node.js 4.0 or higher to run.

> # for use in npm scripts
> npm install electron-packager --save-dev

> # for use from cli
> npm install electron-packager -g

The question is: Is this needed? I'm not sure, maybe @GregorBiswanger knows more.

**Comment by GregorBiswanger** [comment]
The **electron packer** build our Electron.Host project with its own node_modules to the executible electron app. When you install the electron packer into the Electron.Host, your electron app has an unnecessary library. The problem is, you get a bigger file size of your application.

One alternative is, to install this to your ASP.NET Core project. But I dont know, if the people would like a node_modules folder in their ASP.NET project.

**Comment by robertmuehsig** [comment]
So, this [line](https://github.com/ElectronNET/Electron.NET/blob/master/ElectronNET.CLI/Commands/BuildCommand.cs#L64) is needed: 

     ProcessHelper.CmdExecute("npm install electron-packager --global", tempPath);

and we can't use:

     ProcessHelper.CmdExecute("npm install electron-packager", tempPath);

right?

**Comment by GregorBiswanger** [comment]
Mhhh.. we can use the tempPath (Obj folder?).. but we need a own package.json, not from the ElectronNET.Host...
