### ISSUE TITLE
Add ability to pass an argument for "Version" for both the "dotnet publish" and "electron-builder" commands

### ISSUE THREAD

**Issue by tub5** [ElectronNET/Electron.NET#543]
As I'm using Azure DevOps to build the electron app I would like to be able to pass the version of the app as an argument to both the argument for `dotnet publish` and `electron-builder` processes. By adding in the `/Version` argument it will be possible to update both of these via the build pipeline. In regards to the `electrion-builder` process, if the `/Version` argument is provided and there is a value for `buildVersion` then the `/Version` value will take precedence.

**Comment by BenjaminVettori** [comment]
I had the same idea and just saw you already created a PR.
This will provide the ability to use e.g. gitversion to do the versioning automatically instead of having to update the manifest file with a script.

My workaround was the following powershell script, but the extra /Version argument is much more convenient

```
$manifest = Get-Content './electron.manifest.json' -raw | ConvertFrom-Json
$buildVersion = $manifest.build.buildVersion
$gitVersion = gitversion | ConvertFrom-Json
$manifest.build.buildVersion = $gitVersion.SemVer
$manifest | ConvertTo-Json -depth 32 | set-content './electron.manifest.json'
try {
	electronize build /target win
} finally {
	$manifest.build.buildVersion = $buildVersion
	$manifest | ConvertTo-Json -depth 32 | set-content './electron.manifest.json'
}
```
