### ISSUE TITLE
Electronize startup exception.

### ISSUE THREAD

**Issue by MichielArkema** [ElectronNET/Electron.NET#604]
For starters, the installation did not bring the manifest json nor the about@2x.png image.

After fixing those issues I stumbled upon a new one when executing the electronize start command. 

Error:

![image](https://user-images.githubusercontent.com/53873421/133069254-15cf86ff-b316-4698-89bd-6fed32ef2fd5.png)

Hopefully someone is able to help me.

**Comment by NicolasEhrhard** [comment]
Same probleme here #602 . Hope someone has already resolved this

**Comment by MichielArkema** [comment]
> Same probleme here #602 . Hope someone has already resolved this

Unfortunately I haven't been able to fix it yet.  It seems a problem with the installation process in Electron.NET

**Comment by towerbit** [comment]
+1

**Comment by Somfic** [comment]
Having this error when doing `electronize start`, project works fine when using `electronize  start /watch` :/

**Comment by ggomarighetti** [comment]
I found the solution.

What you need is to change the configuration of the project, that error gives it to you because Electronize what it is to use the already compiled project.

To solve this you have to go to your project (Example: Client), right click and look where it says Properties, then, you go to Application -> General -> Assembly name, you should see something like "$ (MSBuildProjectName)" , there you change it to be the same one you entered in electron.manifest.json

**Comment by danatcofo** [comment]
@MichielArkema if @ggomarighetti 's solution fixes your problem can you close this ticket please?

**Comment by peter-bozovic** [comment]
Check the output folder of the build: `Desktop\win-unpacked\resources\bin`
Check the `.exe` file that you have there, and make sure you have the same name in the `electron.manifest.json` under `"executable":"..."`

**Comment by mcrio** [comment]
> To solve this you have to go to your project (Example: Client), right click and look where it says Properties, then, you go to Application -> General -> Assembly name, you should see something like "$ (MSBuildProjectName)" , there you change it to be the same one you entered in electron.manifest.json

This could be part of the docs. @ggomarighetti I could file a PR but don't want to take all the fame away from you :)

**Comment by damikun** [comment]
For people whe searching for solution... Please make sure the `  "executable": "YourNamespaeName",` match the `<AssemblyName>YourNamespaeName</AssemblyName>`  from your `.csproj` file... 

Also make sure that you dont use whitespaces there because electron removes it and than app does not know what `exe` file to run....

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
