### ISSUE TITLE
Images are blury on blazor server

### ISSUE THREAD

**Issue by HeroinGyrl** [ElectronNET/Electron.NET#643]
whenever I use a image its blury. somehow electrons whole app is blury and not like on the browser.
does someone have this same issue?

**Comment by ggomarighetti** [comment]
can you share the steps to reproduce it, try to add more information to the issue, you can try to look at the browser console by pressing CTRL + SHIFT+ I (i).

**Comment by HeroinGyrl** [comment]
@ggomarighetti there is no error or any errors in the console. I think i figured out the problem. when scaling images it makes it blury but really blury. somehow when I use it in my browser it looks normally but on electron it looks blury

**Comment by HeroinGyrl** [comment]
ok the problem is the chrome browser that electron uses on firefox the images are normally. on chrome blury

**Comment by ggomarighetti** [comment]
> 

@HeroinGyrl In this case I understand or at least I think, that your problem is related to the content of your website (html, js, css) and no longer has to do with the code related to Electron and / or ElectronNET.

While it is true that they use chromium for rendering, and would not have to do directly with functionality of the projects already mentioned this the problem.
