### ISSUE TITLE
Startup performance is slow

### ISSUE THREAD

**Issue by vinaykulkarni89** [ElectronNET/Electron.NET#662]
Application is taking nearly 90 seconds to start, post installation. Using Electron latest version and .Net Core 5

**Comment by ggomarighetti** [comment]
It is something that is known, and that will be sought to be optimized in the next updates, as the creators of the repo said, as an aid the "splashscreen" was introduced, which is shown during the loading process of the application, so that the user does not think that the application did not start or that it froze.

**Comment by vinaykulkarni89** [comment]
Hi @ggomarighetti thanks for the comment, I have enabled the splashscreen, however, the 90 seconds time seems to be higher so was looking for the help.
Thanks for putting the light on this as known issue, will wait for the updates.
@GregorBiswanger  thanks for this Electorn.Net

**Comment by GregorBiswanger** [comment]
Unfortunately, malware developers use Electron too. So that under Windows the Windows Defender slows down the start. The only solution here would be to exclude realtime for your own app or to buy a certificate.

As a great comparison, open Visual Studio Code... and open a new, unknown electron app.. four seconds are only slowed down by windows defender.. a shame, because electron is based on the image, although electron is extremely powerful..

**Comment by vinaykulkarni89** [comment]
Hi @GregorBiswanger thanks, will check adding to the exclusion of Defender and report back the status

**Comment by vinaykulkarni89** [comment]
@GregorBiswanger  checked adding to exclusion, there was very minor improvement seen, like out of 90 secs 20 secs were reduced

**Comment by GregorBiswanger** [comment]
Then there can be several other reasons that delay a startup. The most important rule is: measure. You need to profile where exactly the lag is happening. Is it the startup of .net? In most cases: yes. Because Electron is incredibly fast active.

**Comment by GregorBiswanger** [comment]
It often helps to reproduce the problem. If you can reproduce a "Hello World" and provide it to me on github, I'm happy to help.

**Comment by GregorBiswanger** [comment]
It is important to consider Windows Defender for the new project again.

**Comment by vinaykulkarni89** [comment]
Thanks will check with the suggestions and update here
