### ISSUE TITLE
nuget & generell updates

### ISSUE THREAD

**Issue by HeroinGyrl** [ElectronNET/Electron.NET#671]
I've seen many pull requests and forks of this, will be there be any updates on nuget or generally?

**Comment by danatcofo** [comment]
When the repo owners decide to stamp a new version, the related nuget packages available will be updated.  Last one was 7 months ago.  We have a lot of large PR's in the pipeline here and getting them all to play nicely and for them to test them all with what they do seems to be taking a little bit of time.

**Comment by GregorBiswanger** [comment]
In order to maintain the quality, a lot of work has to be put into the PRs. In addition, there are also announcements for the next Electron and .NET releases, these are also still awaited for a big leap.

Then there is family and work, which are now prioritized. A big thank you also to @danatcofo, who is so active here!
