### ISSUE TITLE
Prevent electron duplicate Window

### ISSUE THREAD

**Issue by AvinashSuresh12** [ElectronNET/Electron.NET#677]
Whenever doing any one of the below 3 actions in NavMenu page(NavLink), a new duplicate Electron window is popped up with the page selected. But In my application I would like to disable this behavior as I want only one window to be displayed all the time. Please let me know any fix for the issue.

1."Ctrl+Click"
2."Shift+Click"
3."Alt+Click"

**Comment by danatcofo** [comment]
Yah this hit me as well... very annoying.  What I found was that i was using a pattern of `<a href="#"></a>` in many places and overriding the on click event to do my desired action. As soon as I removed the `href="#"` from the tag the behavior i desired occurred because the browser window didn't see the link as a valid link.  We are ultimately in a browser window here with some extra features available so the rules of a browser window still apply. My search fu didnt find a better way to precent this built in behavior.  If you find a better way let me know.

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
