### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by richardhauer** [ElectronNET/Electron.NET#691]
Note: S/O is not the place for this sort of question.

It has been almost a year since there has been an update to this project and in that time many dependencies have been updated many times, e.g. the version of Electron is now a long way out of date (13.5 vs 18.2). Further there are more than 60 active bugs some of which are several years old.

In light of MAUI hitting its RC milestone is this project going to be abandoned? There does not seem to be any active work on this project at present and we are looking at whether to use this for production software.

Would be good to hear from one of the maintainers of this repo on whether this project has a future...

EDIT: I've noticed there are commits being merged as recently as a couple of weeks ago.  Any chance there is going to be a new version published to nuGet soon? There are fixes in there that I need - I'm sure many people do

**Comment by GregorBiswanger** [comment]
yes, the project is still alive. We've recently made a major switch to a different socket library and have received a lot of PR. Since quality is my top priority, we don't just rush out the latest versions.

In addition to the delay, I have to do my job full-time and am a father of two children. Donations for the project are not received either, so that I can prioritize it even higher.

I currently have to get the project running again, due to the numerous PRs, and then nothing stands in the way of the next big update. Please just be patient.

**Comment by richardhauer** [comment]
OK sounds good - we are having specific pain with printing (options do not seem to get passed to the printer) and there's a bug caused by opening multiple windows that may have been fixed.  We are hosting a net6 Blazor app in ElectronNET which, for the most part, works really well except these cases which are small but important.
