### ISSUE TITLE
How to build: Blazor+Electron.NET desktop app?

### ISSUE THREAD

**Issue by ZedZipDev** [ElectronNET/Electron.NET#699]
🚨 The issue tracker is not for questions 🚨

I am trying to find the readme: how to build Blazer+Electron.NET sample Desktop application: 
1.
2.
...
N.
For example, this Blazor app
https://github.com/edandersen/blazor-desktop-crossplatform-sample

**Comment by ggomarighetti** [comment]
#### Resume
You must understand that Blazor and Electron.NET are two totally different things, Blazor (in this case Blazor Server) is your entire web application, and Electron.NET is just a "host" that creates a new window of a custom program for the client to consume that web application.

You should first focus on developing your web application as such, and then add Electron.NET to the project so that you can package it as an application and distribute it.

The step-by-step on how to add Electron.NET is in the Readme of the repository, it doesn't take much more than that.

Translated with www.DeepL.com/Translator (free version)

**Comment by Oleg26Dev** [comment]
Ok, thanx, I see. 
I mean exactly this: step by step how to add electron to my (Blazor, ASP.NET) app..

**Comment by GregorBiswanger** [comment]
https://youtu.be/6MjxgbmTAAM
